services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: iot_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=default
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: iot_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: iot_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=iot_db
      - POSTGRES_USER=iot_user
      - POSTGRES_PASSWORD=iot_password
    # Persistent data storage
    # volumes:
    #   - iot_postgres_data: *PATH*
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_user -d iot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: iot_fastapi
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  alert_worker:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: iot_alert_server_send
    command: python alert_server_send.py
    depends_on:
      rabbitmq:
        condition: service_healthy

  db_history_worker:
    build:
      context: .
      dockerfile: Dockerfile.workers
    container_name: iot_db_worker
    command: python db_worker.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy